config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'movies#index'

  resources :movies, only: [:index, :show] do
    member do
      get 'reservation'
      get 'show_schedules'
    end
    resources :schedules, only: [:show] do
      resources :reservations, only: [:new, :create]
    end
    resources :reviews, only: [:index, :create, :destroy]
  end
  namespace :admin do
    resources :movies, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :movie_cinemas, only: [:show, :create, :destroy] do
        resources :schedules, only: [:new, :create, :edit, :update, :destroy]
      end
    end
    resources :schedules, only: [:index, :show]
    resources :reservations, only: [:index, :show, :new, :create, :update, :destroy]
  end

  resources :sheets, only: [:index]

  resources :rankings, only: [:index]

  resources :reservations, only: [:new, :create]
  # テスト用ルーティング
end

app/controllers/admin/movies_controller.rb
class Admin::MoviesController < ApplicationController

  before_action :check_if_admin

  def index
    @movies = Movie.all
    
    # @movies内の各映画のIDを抽出し、配列化します
    # 抽出した映画IDを使用して、Scheduleモデルのレコードを検索し、@schedulesに代入します
    # これにより、@schedulesは指定された映画に関連するスケジュールのコレクションとなります
    @schedules = Schedule.where(movie_id: @movies.map(&:id))
  end


  def new
    @movie = Movie.new
  end

  def show
    @movie = Movie.find(params[:id])
    @cinemas = Cinema.all
  end

  def create
    @movie = Movie.new(movie_params)
  
    if @movie.save
      redirect_to "/"
    else
      render :new
    end
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update(movie_params)
      redirect_to "/"
    else
      render :edit
    end
  end

  def destroy

    @movie = Movie.find(params[:id])

    @movie.delete
    redirect_to "/"
  end

  private

  def movie_params
    params.require(:movie).permit(:name, :year, :description, :image_url, :is_showing)
  end
  
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_action :authenticate_user!, except: [:show, :index]

  def index
    @movies = Movie.all
    if params[:is_showing].present?
      @movies = @movies.where(is_showing: params[:is_showing])
    end
    if params[:keyword].present?
      @movies = @movies.where('name LIKE ? OR description LIKE ?', "%#{params[:keyword]}%", "%#{params[:keyword]}%")
    end

    @rankings = Ranking.where(date: Date.today)
  end

  def show
    @movie = Movie.includes(movie_cinemas: :schedules).find(params[:id])
    @available_movie_cinemas = @movie.movie_cinemas.select do |movie_cinema|
      movie_cinema.schedules.present?
    end
  end

  def reservation
    if params[:date].blank? || params[:schedule_id].blank?
      redirect_to movies_path
    else
      @sheets = Sheet.all
      @date = params[:date]
      @schedule = Schedule.find(params[:schedule_id])
      @movie = @schedule.movie_cinema.movie

      @booked_reservations = @schedule.reservations.where(date: @date)
      @booked_reservations_sheet_ids = @booked_reservations.pluck(:screen_sheet_id)
      test
    end
  end

  def show_schedules
    @movie_cinema = MovieCinema.find(params[:movie_cinema_id])
    @dates = (Date.today..Date.today + 6.days).to_a
  end




  #複雑なメソッド
  def test
    @candidate_screen_sheets = []
    @sheets.each do |sheet|
      screen_sheets = ScreenSheet.where(sheet_id: sheet.id)
      screen_sheets.each do |screen_sheet|
          # 座席に対してスクリーン1,2,3全て予約済みだったらbreak
        if count_sheets(sheet) == 3
          @candidate_screen_sheets.push("予約不可")
          break
        end
        # 該当のスクリーンが予約されていなければbreak
        unless is_screen_reserved?(screen_sheet)
          @candidate_screen_sheets.push(screen_sheet)
          break
        end
      end
    end
  end

  # シートidが一致しているものの数を数える
  def count_sheets(sheet)
    count = 0
    @booked_reservations.each do |reservation|
      screen_sheet = ScreenSheet.find(reservation.screen_sheet_id)
      if screen_sheet.sheet_id == sheet.id
        count += 1
      end
    end
    count
  end

  def is_screen_reserved?(screen_sheet)
    @booked_reservations.any? { |reservation| reservation.screen_sheet_id == screen_sheet.id }
  end






  #showアクションを消してreservationアクションを追加する

end

app/helpers/admin/movies_helper.rb
module Admin::MoviesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/index.html.erb
<h1>映画予約サイト</h1>

<br>


<h2>ランキング</h2>
<div class="row">
  <% @rankings.order(reservation_count: :desc).limit(5).each_with_index do |ranking, index| %>
    <div class="col-md-4" style="width: 18rem;">
      <div class="card mb-4">
        <img class="card-img-top" src="https://picsum.photos/100/100" alt="<%= ranking.movie.name %> Image" >
        <div class="card-body">
          <h5 class="card-title">
            <%= link_to "#{index + 1}位: #{ranking.movie.name} (#{ranking.reservation_count}予約)", movie_path(ranking.movie) %>
          </h5>
          <p class="card-text"><%= "#{ranking.movie.year}年公開" %></p>
          <p class="card-text"><%= ranking.movie.description %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<br>

<h2>映画一覧</h2>

<%= form_with(url: movies_path, method: :get, local: true) do |f| %>
  <%= f.radio_button :is_showing, '', checked: params[:is_showing].blank? %> <%= f.label :is_showing_all, 'すべて' %>
  <%= f.radio_button :is_showing, '0', checked: params[:is_showing] == '0' %> <%= f.label :is_showing_soon, '公開予定' %>
  <%= f.radio_button :is_showing, '1', checked: params[:is_showing] == '1' %> <%= f.label :is_showing_now, '公開中' %>
  <%= f.text_field :keyword, value: params[:keyword], placeholder: 'Search' %>
  <%= f.submit 'Filter' %>
<% end %>


<div class="row">
  <% @movies.each do |movie| %>
    <div class="col-md-4" style="width: 18rem;">
      <div class="card mb-4">
        <% if movie.image_url.present? %>
          <img class="card-img-top" src="https://picsum.photos/100/100" alt="<%= movie.name %> Image" >
        <% else %>
          <div class="card-body">
            <p class="card-text">No image available</p>
          </div>
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= link_to movie.name, movie_path(movie) %></h5>
          <p class="card-text"><%= "#{movie.year}年公開" %></p>
          <p class="card-text"><%= movie.description %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/movies/reservation.erb
<h1>座席選択</h1>
<table>
  <tbody>
    <% @sheets.group_by(&:row).each do |row, sheets| %>
      <tr>
        <% sheets.each do |sheet| %>
          <td>
            <% candidate_screen_sheet = @candidate_screen_sheets[sheet.id - 1] %>
            <% if candidate_screen_sheet == "予約不可" %>
              <div class="seat unavailable">
                <%= "#{sheet.row}-#{sheet.column}" %>
              </div>
            <% else %>
              <div class="seat">
                <%= link_to "#{sheet.row}-#{sheet.column}", 
                    new_movie_schedule_reservation_path(@movie, @schedule, date: @date,
                    screen_sheet_id: candidate_screen_sheet.id
                    ) %>
              </div>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to '戻る', movie_path(@movie) %>

app/views/movies/show.html.erb
<h1><%= @movie.name %> (<%= @movie.year %>)</h1>

<% if @movie.image_url.present? %>
  <img src="https://picsum.photos/100/100" alt="<%= @movie.name %> Image" style="width:100px;height:auto;">
<% else %>
  <p>No image available</p>
<% end %>

<p><%= @movie.description %></p>

<% if @available_movie_cinemas.present? %>

  <%= form_with url: show_schedules_movie_path(@movie), method: :get do |form| %>

    <div>
      <label for="schedule">劇場:</label>
      <%= form.select :movie_cinema_id, options_from_collection_for_select(@available_movie_cinemas, "id", ->(movie_cinema) { movie_cinema.cinema.name }) %>
    </div>

    <div>
      <%= form.button 'スケジュールを確認する' %>
    </div>
  <% end %>

<% end %>

<h2>上映劇場一覧</h2>
<table>
  <thead>
    <tr>
      <th>劇場名</th>
    </tr>
  </thead>
  <tbody>
    <% @available_movie_cinemas.each do |movie_cinema| %>
      <tr>
        <td><%= movie_cinema.cinema.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'レビューを見る', movie_reviews_path(@movie) %>

<br>

<%= link_to '映画一覧に戻る', movies_path %>

app/views/movies/show_schedules.erb
<h1><%= @movie_cinema.movie.name %> <%= @movie_cinema.cinema.name %>のスケジュール一覧</h1>


<table>
  <thead>
    <tr>
      <th>Start Time</th>
      <th>End Time</th>
    </tr>
  </thead>
  <tbody>
    <% @movie_cinema.schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.start_time.strftime('%H:%M') %></td>
        <td><%= schedule.end_time.strftime('%H:%M') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= form_with url: reservation_movie_path(@movie_cinema.movie), method: :get do |form| %>

  <div>
    <label for="date">Date:</label>
    <%= form.select :date, options_for_select(@dates.map { |date| [date.strftime('%Y-%m-%d'), date.strftime('%Y-%m-%d')] }) %>
  </div>
  
  <div>
    <label for="schedule">Schedule:</label>
    <%= form.select :schedule_id, options_from_collection_for_select(@movie_cinema.schedules, "id", ->(schedule) { schedule.start_time.strftime('%H:%M') }) %>
  </div>
  <div>
    <%= form.button '座席を予約する' %>
  </div>
<% end %>

<%= link_to '映画一覧に戻る', movies_path %>