config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'movies#index'

  resources :movies, only: [:index, :show] do
    member do
      get 'reservation'
      get 'show_schedules'
    end
    resources :schedules, only: [:show] do
      resources :reservations, only: [:new, :create]
    end
    resources :reviews, only: [:index, :create, :destroy]
  end
  namespace :admin do
    resources :movies, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :movie_cinemas, only: [:show, :create, :destroy] do
        resources :schedules, only: [:new, :create, :edit, :update, :destroy]
      end
    end
    resources :schedules, only: [:index, :show]
    resources :reservations, only: [:index, :show, :new, :create, :update, :destroy]
  end

  resources :sheets, only: [:index]

  resources :rankings, only: [:index]

  resources :reservations, only: [:new, :create]
  # テスト用ルーティング
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :schedule
  belongs_to :screen_sheet

  validates_uniqueness_of :schedule_id, scope: [:screen_sheet_id, :date], message: 'そのスケジュール、シート、日付の組み合わせはすでに予約済みです'
  validates_format_of :email, with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: 'メールアドレスの形式が不正です'
end

app/controllers/admin/reservations_controller.rb
class Admin::ReservationsController < ApplicationController

  before_action :check_if_admin

  def index
    @reservations = Reservation.all.includes(schedule: { movie_cinema: [:movie, :cinema] }, screen_sheet: :screen)
  end

  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservation_params)

    if @reservation.save
      redirect_to admin_reservations_path, notice: '予約が完了しました'
    else
      flash.now[:alert] = '予約の保存に失敗しました'
      render :new, status: :bad_request
    end
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def update
    @reservation = Reservation.find(params[:id])
    if @reservation.update(reservation_params)
      redirect_to admin_reservations_path, notice: '予約を更新しました'
    else
      flash.now[:alert] = '予約の保存に失敗しました'
      render :show, status: :bad_request
    end
  end

  def destroy

    @reservation = Reservation.find(params[:id])

    @reservation.delete
    redirect_to admin_reservations_path
  end

  private

  def reservation_params
    params.require(:reservation).permit(:date, :schedule_id, :screen_sheet_id, :name, :email)
  end

  
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  before_action :authenticate_user!

  def new
    if params[:date].blank? || params[:screen_sheet_id].blank?
      redirect_to movies_path
    else
      @reservation = Reservation.new(date: Date.parse(params[:date]), screen_sheet_id: params[:screen_sheet_id].to_i, schedule_id: params[:schedule_id].to_i)
  
      @reservation_movie_name = @reservation.schedule.movie_cinema.movie.name
      @reservation_cinema_name = @reservation.schedule.movie_cinema.cinema.name
      @reservation_date = @reservation.date
      @reservation_sheet = "#{@reservation.screen_sheet.sheet.row}-#{@reservation.screen_sheet.sheet.column}"
      @reservation_schedule = "#{@reservation.schedule.start_time.strftime('%H:%M')}-#{@reservation.schedule.end_time.strftime('%H:%M')}"
    end
  end

  def create
    @reservation = Reservation.new(reservation_params)
  
    if @reservation.save
      ReservationMailer.reservation_completed(@reservation).deliver_now
      redirect_to movies_path, notice: '予約が完了しました'
    else
      redirect_to reservation_movie_path(id: @reservation.schedule.movie.id, schedule_id: @reservation.schedule.id, date: @reservation.date)
    end
  
  end
  
  private
  
  def reservation_params
    params.require(:reservation).permit(:date, :schedule_id, :screen_sheet_id, :email, :name)
  end


end

app/helpers/admin/reservations_helper.rb
module Admin::ReservationsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/admin/reservations/index.html.erb
<h1>予約一覧</h1>

<%= link_to '新規予約作成', new_admin_reservation_path, class: 'btn btn-primary' %>

<table>
  <thead>
    <tr>
      <th>予約ID</th>
      <th>予約受付時刻</th>
      <th>案内日</th>
      <th>映画作品</th>
      <th>劇場</th>
      <th>スクリーン</th>
      <th>座席</th>
      <th>名前</th>
      <th>メールアドレス</th>
    </tr>
  </thead>
  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= link_to reservation.id, admin_reservation_path(reservation) %></td>
        <td><%= reservation.created_at.strftime("%Y-%m-%d %H:%M") %></td>
        <td><%= reservation.date %></td>
        <td><%= reservation.schedule.movie_cinema.movie.name %></td>
        <td><%= reservation.schedule.movie_cinema.cinema.name %></td>
        <td><%= reservation.screen_sheet.screen.id %></td>
        <td><%= "#{reservation.screen_sheet.sheet.row}-#{reservation.screen_sheet.sheet.column}" %></td>
        <td><%= reservation.name %></td>
        <td><%= reservation.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/reservations/new.html.erb
<h1>新規予約作成</h1>

<%= form_with(model: @reservation, url: admin_reservations_path, method: :post) do |form| %>
  <div class="form-group">
    <%= form.label :date, '日付' %>
    <%= form.date_field :date, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :schedule_id, 'スケジュールID' %>
    <%= form.number_field :schedule_id, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :screen_sheet_id, '座席ID' %>
    <%= form.number_field :screen_sheet_id, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :name, '名前' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :email, 'メールアドレス' %>
    <%= form.email_field :email, class: 'form-control' %>
  </div>

  <%= form.submit '予約する', class: 'btn btn-primary' %>
<% end %>

app/views/admin/reservations/show.html.erb
<h1>予約詳細・編集</h1>
<%= form_with(model: @reservation, url: admin_reservation_path(@reservation), method: :patch, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :date, '日付' %>
    <%= form.date_field :date, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :schedule_id, 'スケジュールID' %>
    <%= form.number_field :schedule_id, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :screen_sheet_id, '座席ID' %>
    <%= form.number_field :screen_sheet_id, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :name, '名前' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :email, 'メールアドレス' %>
    <%= form.email_field :email, class: 'form-control' %>
  </div>

  <%= form.submit '保存する', class: 'btn btn-primary' %>
<% end %>

<%= link_to 'Delete Reservation', admin_reservation_path(@reservation), method: :delete, data: { confirm: 'Are you sure?' } %>