config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'movies#index'

  resources :movies, only: [:index, :show] do
    member do
      get 'reservation'
      get 'show_schedules'
    end
    resources :schedules, only: [:show] do
      resources :reservations, only: [:new, :create]
    end
    resources :reviews, only: [:index, :create, :destroy]
  end
  namespace :admin do
    resources :movies, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :movie_cinemas, only: [:show, :create, :destroy] do
        resources :schedules, only: [:new, :create, :edit, :update, :destroy]
      end
    end
    resources :schedules, only: [:index, :show]
    resources :reservations, only: [:index, :show, :new, :create, :update, :destroy]
  end

  resources :sheets, only: [:index]

  resources :rankings, only: [:index]

  resources :reservations, only: [:new, :create]
  # テスト用ルーティング
end

app/controllers/admin/movies_controller.rb
class Admin::MoviesController < ApplicationController

  before_action :check_if_admin

  def index
    @movies = Movie.all
    
    # @movies内の各映画のIDを抽出し、配列化します
    # 抽出した映画IDを使用して、Scheduleモデルのレコードを検索し、@schedulesに代入します
    # これにより、@schedulesは指定された映画に関連するスケジュールのコレクションとなります
    @schedules = Schedule.where(movie_id: @movies.map(&:id))
  end


  def new
    @movie = Movie.new
  end

  def show
    @movie = Movie.find(params[:id])
    @cinemas = Cinema.all
  end

  def create
    @movie = Movie.new(movie_params)
  
    if @movie.save
      redirect_to "/"
    else
      render :new
    end
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update(movie_params)
      redirect_to "/"
    else
      render :edit
    end
  end

  def destroy

    @movie = Movie.find(params[:id])

    @movie.delete
    redirect_to "/"
  end

  private

  def movie_params
    params.require(:movie).permit(:name, :year, :description, :image_url, :is_showing)
  end
  
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_action :authenticate_user!, except: [:show, :index]

  def index
    @movies = Movie.all
    if params[:is_showing].present?
      @movies = @movies.where(is_showing: params[:is_showing])
    end
    if params[:keyword].present?
      @movies = @movies.where('name LIKE ? OR description LIKE ?', "%#{params[:keyword]}%", "%#{params[:keyword]}%")
    end

    @rankings = Ranking.where(date: Date.today)
  end

  def show
    @movie = Movie.includes(movie_cinemas: :schedules).find(params[:id])
    @available_movie_cinemas = @movie.movie_cinemas.select do |movie_cinema|
      movie_cinema.schedules.present?
    end
  end

  def reservation
    if params[:date].blank? || params[:schedule_id].blank?
      redirect_to movies_path
    else
      @sheets = Sheet.all
      @date = params[:date]
      @schedule = Schedule.find(params[:schedule_id])
      @movie = @schedule.movie_cinema.movie

      @booked_reservations = @schedule.reservations.where(date: @date)
      @booked_reservations_sheet_ids = @booked_reservations.pluck(:screen_sheet_id)
      test
    end
  end

  def show_schedules
    @movie_cinema = MovieCinema.find(params[:movie_cinema_id])
    @dates = (Date.today..Date.today + 6.days).to_a
  end




  #複雑なメソッド
  def test
    @candidate_screen_sheets = []
    @sheets.each do |sheet|
      screen_sheets = ScreenSheet.where(sheet_id: sheet.id)
      screen_sheets.each do |screen_sheet|
          # 座席に対してスクリーン1,2,3全て予約済みだったらbreak
        if count_sheets(sheet) == 3
          @candidate_screen_sheets.push("予約不可")
          break
        end
        # 該当のスクリーンが予約されていなければbreak
        unless is_screen_reserved?(screen_sheet)
          @candidate_screen_sheets.push(screen_sheet)
          break
        end
      end
    end
  end

  # シートidが一致しているものの数を数える
  def count_sheets(sheet)
    count = 0
    @booked_reservations.each do |reservation|
      screen_sheet = ScreenSheet.find(reservation.screen_sheet_id)
      if screen_sheet.sheet_id == sheet.id
        count += 1
      end
    end
    count
  end

  def is_screen_reserved?(screen_sheet)
    @booked_reservations.any? { |reservation| reservation.screen_sheet_id == screen_sheet.id }
  end






  #showアクションを消してreservationアクションを追加する

end

app/helpers/admin/movies_helper.rb
module Admin::MoviesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/admin/movies/edit.html.erb
<h1>映画を編集する</h1>

<%= form_with(model: @movie, url: admin_movie_path(@movie), method: :patch, local: true) do |form| %>
  <!-- フォームフィールドの入力 -->
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :year %>
  <%= form.text_field :year %>

  <%= form.label :description %>
  <%= form.text_area :description %>

  <%= form.label :image_url %>
  <%= form.text_field :image_url %>

  <%= form.label :is_showing %>
  <%= form.check_box :is_showing %>

  <%= form.submit "Update Movie" %>
<% end %>

<%= link_to 'この映画を削除する', admin_movie_path(@movie), method: :delete, data: { confirm: 'Are you sure?' } %>

<%= link_to '戻る', admin_movies_path %>

app/views/admin/movies/index.html.erb
<h1>管理ページ 映画一覧</h1>

<div class="row">
  <% @movies.each do |movie| %>
    <div class="col-md-4" style="width: 18rem;">
      <div class="card mb-4">
        <% if movie.image_url.present? %>
          <img class="card-img-top" src="https://picsum.photos/100/100" alt="<%= movie.name %> Image">
        <% else %>
          <div class="card-body">
            <p class="card-text">No image available</p>
          </div>
        <% end %>
        <div class="card-body">
          <h5 class="card-title">
            <%= link_to movie.name, edit_admin_movie_path(movie) %>
          </h5>
          <p class="card-text"><%= movie.year %></p>
          <p class="card-text"><%= movie.description %></p>
          <p class="card-text">
            <%= link_to "上映劇場を確認する", admin_movie_path(movie) %>
          </p>
        

        </div>
      </div>
    </div>
  <% end %>
</div>

<%= link_to '映画を追加する', new_admin_movie_path %>

<br>

<%= link_to '予約一覧を確認する', admin_reservations_path %>

app/views/admin/movies/new.html.erb
<h1>映画を追加する</h1>

<%= form_with(model: @movie, local: true, url: "/admin/movies")do |form| %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :year %>
    <%= form.text_field :year %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div>
    <%= form.label :is_showing %>
    <%= form.check_box :is_showing %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<%= link_to '戻る', admin_movies_path %>

app/views/admin/movies/show.html.erb
<h1><%= @movie.name %> (<%= @movie.year %>)</h1>

<% if @movie.image_url.present? %>
  <img src="https://picsum.photos/100/100" alt="<%= @movie.name %> Image" style="width:100px;height:auto;">
<% else %>
  <p>No image available</p>
<% end %>

<p><%= @movie.description %></p>

<br>

<h2>上映劇場一覧</h2>
<table>
  <thead>
    <tr>
      <th>上映劇場</th>
    </tr>
  </thead>
  <tbody>
    <% @movie.movie_cinemas.each do |movie_cinema| %>
      <tr>
        <td><%= link_to movie_cinema.cinema.name, admin_movie_movie_cinema_path(@movie, movie_cinema) %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>
<h3>上映劇場の追加</h3>
<%= form_with url: admin_movie_movie_cinemas_path(@movie), method: :post do |form| %>

  <div>
    <label for="cinema">Cinema:</label>
    <%= form.select :cinema_id, options_from_collection_for_select(@cinemas, "id", ->(cinema) { cinema.name}) %>
  </div>

  <div>
    <%= form.button '上映劇場を追加する' %>
  </div>
<% end %>





<br>
<%= link_to '戻る', admin_movies_path %>