config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'movies#index'

  resources :movies, only: [:index, :show] do
    member do
      get 'reservation'
      get 'show_schedules'
    end
    resources :schedules, only: [:show] do
      resources :reservations, only: [:new, :create]
    end
    resources :reviews, only: [:index, :create, :destroy]
  end
  namespace :admin do
    resources :movies, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :movie_cinemas, only: [:show, :create, :destroy] do
        resources :schedules, only: [:new, :create, :edit, :update, :destroy]
      end
    end
    resources :schedules, only: [:index, :show]
    resources :reservations, only: [:index, :show, :new, :create, :update, :destroy]
  end

  resources :sheets, only: [:index]

  resources :rankings, only: [:index]

  resources :reservations, only: [:new, :create]
  # テスト用ルーティング
end

app/models/movie_cinema.rb
class MovieCinema < ApplicationRecord
  belongs_to :movie
  belongs_to :cinema
  has_many :schedules, dependent: :destroy

  validates_uniqueness_of :movie_id, scope: :cinema_id, message: 'その組み合わせはすでに追加済みです'
end

app/controllers/admin/movie_cinemas_controller.rb
class Admin::MovieCinemasController < ApplicationController

  before_action :check_if_admin

  def create
    @movie_cinema = MovieCinema.new(movie_cinema_params)

    if @movie_cinema.save
      redirect_to admin_movie_path(@movie_cinema.movie)
    else
      redirect_to admin_movie_path(@movie_cinema.movie)
    end
  end

  def show
    @movie_cinema = MovieCinema.find(params[:id])
  end

  def destroy
    @movie_cinema = MovieCinema.find(params[:id])
    if @movie_cinema.destroy
      flash[:notice] = '映画館での上映が正常に削除されました'
    else
      flash[:alert] = '映画館での上映を削除することができませんでした'
    end
    redirect_to admin_movie_path(@movie_cinema.movie)
  end




  private

  def movie_cinema_params
    params.permit(:movie_id, :cinema_id)
  end


end

app/helpers/admin/movie_cinemas_helper.rb
module Admin::MovieCinemasHelper
end

app/views/admin/movie_cinemas/show.html.erb
<h1><%= @movie_cinema.movie.name %> (<%= @movie_cinema.cinema.name %>)</h1>

<h2>上映スケジュール一覧</h2>
<table>
  <thead>
    <tr>
      <th>スケジュールID</th>
      <th>上映開始</th>
      <th>上映終了</th>
    </tr>
  </thead>
  <tbody>
    <% @movie_cinema.schedules.each do |schedule| %>
      <tr>
        <td><%= link_to schedule.id, edit_admin_movie_movie_cinema_schedule_path(@movie_cinema.movie, @movie_cinema, schedule) %></td>
        <td><%= schedule.start_time.strftime('%H:%M') %></td>
        <td><%= schedule.end_time.strftime('%H:%M') %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'スケジュールを追加する', new_admin_movie_movie_cinema_schedule_path(@movie_cinema.movie, @movie_cinema) %>
<br>
<%= link_to 'この映画館での上映を削除する', admin_movie_movie_cinema_path(@movie_cinema), method: :delete, data: { confirm: '本当に削除しますか？' } %>
<br>
<%= link_to "戻る", admin_movie_path(@movie_cinema.movie) %>